# Generated by Django 3.1 on 2022-05-23 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FSImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('FSJob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fsapp.fsjob')),
            ],
        ),
    ]
