# Generated by Django 3.1 on 2022-05-23 06:28

from django.db import migrations, models
import fsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0002_fsimage_fsjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsimage',
            name='image',
            field=models.ImageField(upload_to=fsapp.models.get_image_filename, verbose_name='Image'),
        ),
    ]
