# Generated by Django 3.1 on 2022-05-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0003_auto_20220522_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
