# Generated by Django 3.1 on 2022-05-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0004_auto_20220523_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsimage',
            name='image',
        ),
    ]
