# Generated by Django 3.1 on 2022-05-24 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0005_remove_fsimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
