# Generated by Django 3.1 on 2022-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0006_fsimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsimage',
            name='filter_image',
            field=models.ImageField(default='/images/loader-blocks.gif', upload_to=''),
        ),
    ]
