# Generated by Django 3.1 on 2022-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0007_fsimage_filter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsimage',
            name='filter_image',
            field=models.ImageField(blank=True, default='/images/loader-blocks.gif', upload_to=''),
        ),
    ]
