# Generated by Django 3.1 on 2022-07-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0008_auto_20220722_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsimage',
            name='filter_image',
        ),
    ]
