# Generated by Django 3.1 on 2022-07-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0009_remove_fsimage_filter_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSFilteredImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtered_image', models.ImageField(upload_to='')),
                ('FSJob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fsapp.fsjob')),
            ],
        ),
    ]
