# Generated by Django 3.1 on 2022-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0010_fsfilteredimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsfilteredimage',
            name='celery_task_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
