# Generated by Django 3.1 on 2022-08-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0011_fsfilteredimage_celery_task_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
