# Generated by Django 3.1 on 2022-08-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsapp', '0012_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsjob',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
